# Generated by Django 5.2.6 on 2025-09-16 04:38

from django.db import migrations


def populate_cars(apps, schema_editor):
    from djangoapp.populate import initiate

    initiate()


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_cars, migrations.RunPython.noop),
    ]
